# Generated by Django 5.1.15 on 2026-10-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('normalized_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordinate_source', models.CharField(blank=True, max_length=32, null=True)),
                ('coordinates_updated_at', models.DateTimeField(blank=True, null=True)),
                ('effective_price_per_gallon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('effective_price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_fuelst_latitud_e7de73_idx'), models.Index(fields=['state'], name='fuel_fuelst_state_641286_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=11)),
                ('canonical_price_hash', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.CharField(max_length=64)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fuel.fuelstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station'], name='fuel_fuelpr_station_187fea_idx')],
            },
        ),
    ]
